name: Publish
on:
  push:
    branches:
      - main
#  TODO: lock down main pushes
jobs:
  publish:
    concurrency:
      group: publish
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run pkg_build.sh
        run: ./pkg_build.sh
      - name: Commit changes
        run: |
          git add archive/* *.plg
          git commit -m "Publish plg changes"
          git push
